name: brick_converter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  logger: 1.1.0

  json_annotation: ^4.4.0

  file_picker: ^5.2.5

  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  flutter_native_splash: ^2.2.17
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  go_router: ^6.0.1

  flutter_slidable: ^2.0.0

  url_launcher: ^6.1.8

  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  build_runner: ^2.1.7
  json_serializable: ^6.1.4

  flutter_speed_dial: ^6.2.0
  msix: ^2.7.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/color_table.csv
    - assets/gobrick_conversion_table.csv
    - assets/fpe.svg
    - assets/bl_logo.svg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Brick Converter
  publisher_display_name: FPE
  identity_name: de.fpe.brickconverter
  msix_version: 1.0.0.0
  logo_path: C:\develop\brick_converter\assets\fpe.png
  capabilities: internetClient
  certificate_path: C:\develop\brick_converter\brick-converter.pfx
  certificate_password: 123456
  publisher: CN=FPE, O=FPE, C=DE
